server: 
  port: 3344 
  
spring: 
  application: 
    name: springcloud-config-demo
  cloud: 
    config: 
      server: 
        git: 
          uri: git@github.com:xywanhh/springcloud-config-demo.git #GitHub上面的git仓库名字
 